### ISSUE TITLE
Broken admin menu

### ISSUE THREAD

**Issue by FireBird22** [Drifter321/csgo-css-weapon-restrict#1]
The characters/text inside the admin menu seems to be broke.
screenshots below.
https://i.imgur.com/DJ6CqYT.png
https://i.imgur.com/JVk1zsS.png

And it is indeed your plugin, because upon removing the plugin that menu no longer appears

**Comment by ambaca** [comment]
I assume, it's translation files (*.txt)
This can happen in any plugin which use text files to translate or print phrases in menu.

Problem happens when you upload files to server, those text files need transfer in ASCII mode (inside FTP program).
Or otherwise you end up mixing Linux and Windows text files.

Try upload text files again, turn FTP program file transfer to -> ASCII mode, reboot server.
